### ISSUE TITLE
请问com.github.Kermit95:ExUtils:v1.0.7这个引用不存在了吗？

### ISSUE THREAD

**Issue by initialjie** [Kermit95/Today#1]
如题。
另外请问网络请求是放在ActionsCreator做还是Store做比较合适？

**Comment by kaiwk** [comment]
实在抱歉！很久没关注了。

这个库不存在了，已经修正。

网络请求放在ActionCreator比较好，Store用来保存View的状态，而且为了使Store和View保持同步应该尽量避免在Store中做过多的操作。
